version: '3'

services:
  mariadb:
    mem_limit: 8g
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: web
      MYSQL_PASSWORD: web
      MYSQL_DATABASE: web
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    mem_limit: 8g
    ports:
      - "6379:6379"
  bench:
    build:
      context: containers/php
      args:
        USER_ID: "${CUSTOM_USER_ID:-1000}"
        GROUP_ID: "${CUSTOM_GROUP_ID:-1000}"
    volumes:
      - './:/app'
  reporter:
    command: 'php -S 0.0.0.0:8000'
    build:
      context: containers/php
      args:
        USER_ID: "${CUSTOM_USER_ID:-1000}"
        GROUP_ID: "${CUSTOM_GROUP_ID:-1000}"
    ports:
      - "8000:8000"
    volumes:
      - './results:/app'